### ISSUE TITLE
Problem in SLLambda with initial branching

### ISSUE THREAD

**Issue by fhowar** [LearnLib/ralib#79]
The following config leads to an NPE

```
learner=sllambda
target=benchmarks/models/SIP2_1param/model.register.xml
use.eqtest=true
use.ceopt=false
use.suffixopt=true
use.fresh=false
use.rwalk=true
export.model=true
rwalk.prob.fresh=0.1
rwalk.prob.reset=0.05
rwalk.seed.transitions=true
rwalk.max.depth=10
rwalk.max.runs=10000
rwalk.reset.count=false
rwalk.draw.uniform=true
teachers=int:de.learnlib.ralib.tools.theories.IntegerEqualityTheory
random.seed=-5080878705226998718
```

Stacktrace:

```
Execution terminated abnormally: Cannot invoke "de.learnlib.ralib.learning.LocationComponent.getBranching(de.learnlib.ralib.words.ParameterizedSymbol)" because "src_c" is null
java.lang.NullPointerException: Cannot invoke "de.learnlib.ralib.learning.LocationComponent.getBranching(de.learnlib.ralib.words.ParameterizedSymbol)" because "src_c" is null
	at de.learnlib.ralib.learning.AutomatonBuilder.computeTransition(AutomatonBuilder.java:132)
	at de.learnlib.ralib.learning.AutomatonBuilder.computeTransitions(AutomatonBuilder.java:102)
	at de.learnlib.ralib.learning.AutomatonBuilder.toRegisterAutomaton(AutomatonBuilder.java:79)
	at de.learnlib.ralib.learning.ralambda.RaLambda.getHypothesis(RaLambda.java:515)
	at de.learnlib.ralib.tools.IOSimulator.run(IOSimulator.java:303)
	at de.learnlib.ralib.tools.ConsoleClient.run(ConsoleClient.java:80)
	at de.learnlib.ralib.Main.main(Main.java:30)
```

**Comment by fhowar** [comment]
@FredrikTaquist can you look at this?
